"""update IDs naming

Revision ID: cb3141507b54
Revises: dd0e08e48a18
Create Date: 2026-08-28 01:14:33.848670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3141507b54'
down_revision: Union[str, Sequence[str], None] = 'dd0e08e48a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint(op.f('assets_asset_project_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'projects', ['asset_project_id'], ['id'])
    op.drop_column('assets', 'asset_id')
    op.add_column('chunks', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint(op.f('chunks_data_chunk_project_id_fkey'), 'chunks', type_='foreignkey')
    op.drop_constraint(op.f('chunks_data_chunk_asset_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'assets', ['data_chunk_asset_id'], ['id'])
    op.create_foreign_key(None, 'chunks', 'projects', ['data_chunk_project_id'], ['id'])
    op.drop_column('chunks', 'data_chunk_id')
    op.add_column('projects', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('projects', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('projects', 'id')
    op.add_column('chunks', sa.Column('data_chunk_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_data_chunk_asset_id_fkey'), 'chunks', 'assets', ['data_chunk_asset_id'], ['asset_id'])
    op.create_foreign_key(op.f('chunks_data_chunk_project_id_fkey'), 'chunks', 'projects', ['data_chunk_project_id'], ['project_id'])
    op.drop_column('chunks', 'id')
    op.add_column('assets', sa.Column('asset_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_asset_project_id_fkey'), 'assets', 'projects', ['asset_project_id'], ['project_id'])
    op.drop_column('assets', 'id')
    # ### end Alembic commands ###
